version: '3.8'
services:
  ldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: 'MonOrganisation'
      LDAP_DOMAIN: 'monorganisation.com'
      LDAP_ADMIN_PASSWORD: 'admin'
    ports:
      - '389:389'
      - '636:636'
